"""
Shared config surface (source of truth).
"""
from shared.config.paths import (
    MA_DATA_ROOT,
    DATA_PUBLIC_ROOT,
    DATA_PRIVATE_ROOT,
    FEATURES_OUTPUT_ROOT,
    get_private_root,
    get_local_assets_root,
    get_hci_v2_root,
    get_core_spine_root,
    get_yearend_hot100_root,
    get_audio_models_root,
    get_repo_root,
    get_data_root,
    get_calibration_root,
    get_external_data_root,
    get_lyric_intel_db_path,
    get_historical_echo_db_path,
    get_features_output_root,
    get_kaggle_year_end_lyrics_path,
    get_hot100_lyrics_audio_path,
    get_core_1600_csv_path,
    get_hci_v2_targets_csv,
    get_hci_v2_corpus_csv,
    get_hci_v2_training_csv,
    get_hci_v2_training_eval_csv,
    get_hci_v2_overlap_csv,
    get_hci_v2_audio_seed_csv,
    get_audio_hci_v2_model_path,
    get_audio_hci_v2_model_meta_path,
    get_audio_hci_v2_calibration_path,
    get_yearend_hot100_top100_path,
    get_yearend_hot100_top200_path,
    get_spine_root,
    get_spine_backfill_root,
    get_spine_master_csv,
    market_norms_path,
)
from shared.config.audio import (
    DEFAULT_HCI_PROFILE,
    DEFAULT_HCI_CALIBRATION_PATH,
    DEFAULT_MARKET_NORMS_PATH,
    DEFAULT_AUDIO_POLICY_PATH,
    DEFAULT_AUDIO_V2_CALIBRATION_PATH,
    DEFAULT_HCI_V2_TARGETS_CSV,
    DEFAULT_HCI_V2_CORPUS_CSV,
    DEFAULT_HCI_V2_TRAINING_CSV,
    DEFAULT_LOUDNESS_NORMS_LOCAL_PATH,
    DEFAULT_MARKET_NORMS_LOUDNESS_PATH,
    load_json_safe,
    resolve_hci_calibration,
    resolve_market_norms,
    resolve_audio_policy,
    resolve_audio_v2_calibration,
    resolve_hci_v2_targets,
    resolve_hci_v2_corpus,
    resolve_hci_v2_training_out,
    resolve_loudness_norms_out,
)
from shared.config.constants import (
    ERA_BUCKETS,
    ERA_BUCKET_MISC,
    TIER_THRESHOLDS,
    LCI_AXES,
)
from shared.config.neighbors import (
    DEFAULT_NEIGHBORS_LIMIT,
    DEFAULT_NEIGHBORS_DISTANCE,
    DEFAULT_NEIGHBORS_CONFIG_PATH,
    resolve_neighbors_config,
)
from shared.config.pipeline import (
    HCI_BUILDER_PROFILE_DEFAULT,
    NEIGHBORS_PROFILE_DEFAULT,
    SIDECAR_TIMEOUT_DEFAULT,
)
from shared.config.profiles import (
    DEFAULT_LCI_PROFILE,
    DEFAULT_LCI_CALIBRATION_PATH,
    DEFAULT_TTC_PROFILE,
    DEFAULT_TTC_CONFIG_PATH,
    resolve_profile_config,
)
from shared.config.scripts import (
    DEFAULT_REPO_ENV,
    DEFAULT_PYTHON,
    DEFAULT_LYRIC_LCI_PROFILE,
    DEFAULT_LYRIC_LCI_CALIBRATION,
)

__all__ = [
    # paths
    "MA_DATA_ROOT",
    "DATA_PUBLIC_ROOT",
    "DATA_PRIVATE_ROOT",
    "FEATURES_OUTPUT_ROOT",
    "get_private_root",
    "get_local_assets_root",
    "get_hci_v2_root",
    "get_core_spine_root",
    "get_yearend_hot100_root",
    "get_audio_models_root",
    "get_repo_root",
    "get_data_root",
    "get_calibration_root",
    "get_external_data_root",
    "get_lyric_intel_db_path",
    "get_historical_echo_db_path",
    "get_features_output_root",
    "get_kaggle_year_end_lyrics_path",
    "get_hot100_lyrics_audio_path",
    "get_core_1600_csv_path",
    "get_hci_v2_targets_csv",
    "get_hci_v2_corpus_csv",
    "get_hci_v2_training_csv",
    "get_hci_v2_training_eval_csv",
    "get_hci_v2_overlap_csv",
    "get_hci_v2_audio_seed_csv",
    "get_audio_hci_v2_model_path",
    "get_audio_hci_v2_model_meta_path",
    "get_audio_hci_v2_calibration_path",
    "get_yearend_hot100_top100_path",
    "get_yearend_hot100_top200_path",
    "get_spine_root",
    "get_spine_backfill_root",
    "get_spine_master_csv",
    "market_norms_path",
    # audio
    "DEFAULT_HCI_PROFILE",
    "DEFAULT_HCI_CALIBRATION_PATH",
    "DEFAULT_MARKET_NORMS_PATH",
    "DEFAULT_AUDIO_POLICY_PATH",
    "DEFAULT_AUDIO_V2_CALIBRATION_PATH",
    "DEFAULT_HCI_V2_TARGETS_CSV",
    "DEFAULT_HCI_V2_CORPUS_CSV",
    "DEFAULT_HCI_V2_TRAINING_CSV",
    "DEFAULT_LOUDNESS_NORMS_LOCAL_PATH",
    "DEFAULT_MARKET_NORMS_LOUDNESS_PATH",
    "load_json_safe",
    "resolve_hci_calibration",
    "resolve_market_norms",
    "resolve_audio_policy",
    "resolve_audio_v2_calibration",
    "resolve_hci_v2_targets",
    "resolve_hci_v2_corpus",
    "resolve_hci_v2_training_out",
    "resolve_loudness_norms_out",
    # constants
    "ERA_BUCKETS",
    "ERA_BUCKET_MISC",
    "TIER_THRESHOLDS",
    "LCI_AXES",
    # neighbors
    "DEFAULT_NEIGHBORS_LIMIT",
    "DEFAULT_NEIGHBORS_DISTANCE",
    "DEFAULT_NEIGHBORS_CONFIG_PATH",
    "resolve_neighbors_config",
    # pipeline
    "HCI_BUILDER_PROFILE_DEFAULT",
    "NEIGHBORS_PROFILE_DEFAULT",
    "SIDECAR_TIMEOUT_DEFAULT",
    # profiles
    "DEFAULT_LCI_PROFILE",
    "DEFAULT_LCI_CALIBRATION_PATH",
    "DEFAULT_TTC_PROFILE",
    "DEFAULT_TTC_CONFIG_PATH",
    "resolve_profile_config",
    # scripts
    "DEFAULT_REPO_ENV",
    "DEFAULT_PYTHON",
    "DEFAULT_LYRIC_LCI_PROFILE",
    "DEFAULT_LYRIC_LCI_CALIBRATION",
]
